// Generates the committed 20-event synthetic fixture (s2w#371). Fake numbers, fake shas, fake
// branches: nothing here is sampled from a real source. It runs the capture's own builders, so
// the fixture has the exact shape a real capture has.
//
// usage: node --experimental-strip-types fixture.ts [--write]
//   prints the fixture; --write replaces fixture/synthetic-20.sse. The test suite fails if the
//   committed file differs from what this prints.

import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { assertClean } from "./scrub.ts";
import {
  MARK, commitEvents, itemEvents, legEvents, render, seatEvents, sprintEvents, timelineEvents, window,
  type Joins, type Repo,
} from "./events.ts";

export const FIXTURE_PATH = fileURLToPath(new URL("./fixture/synthetic-20.sse", import.meta.url));

const fake = (n: number) => createHash("sha256").update(`synthetic-${n}`).digest("hex").slice(0, 40);

export function synthetic(): string {
  const shas = [1, 2, 3, 4].map(fake);
  const joins: Joins = {
    sha: (_r: Repo, s: string) => shas.find((x) => x.startsWith(s)),
    actor: (l) => (l === "maintainer" ? "maintainer" : "other"),
  };
  const day = "2030-01-02T";
  const legs = legEvents([
    { id: 101, key: "s2w#900", step: "understand", detail: "starting", timestamp: `${day}00:00:00Z` },
    { id: 102, key: "s2w#900", step: "branch", detail: "feat/900-widget", timestamp: `${day}00:01:00Z` },
    { id: 103, key: "s2w#900", step: "implement", detail: `commit @${shas[1].slice(0, 8)}`, timestamp: `${day}00:20:00Z` },
    { id: 104, key: "s2w#900", step: "review-code", detail: "round 1 BLOCK P:- I:o R:f+grok", timestamp: `${day}00:30:00Z` },
    { id: 105, key: "s2w#900", step: "pr", detail: "PR #901 opened", timestamp: `${day}00:41:00Z` },
    { id: 106, key: "s2w#900", step: "done", detail: "PR #901 leg B done", timestamp: `${day}00:59:00Z` },
    { id: 107, key: "other#1", step: "done", detail: "dropped by the repo filter", timestamp: `${day}00:59:30Z` },
  ], joins);
  const branchPr = new Map([["s2w:feat/900-widget", 901]]);
  const seat = (offset: number, verdict: string | null, issue: number | null, ts: string) => ({
    offset, repo: "s2w" as const, ts_start: `${day}${ts}`, ts_end: `${day}${ts}`, engine: "f",
    model: "fable", tier: "judgment", verdict, issue, branch: "feat/900-widget",
    head_sha: shas[1].slice(0, 8), seat_id: `seat-${offset}`, script: "review.sh",
  });
  const seats = seatEvents([
    seat(2030010200001, "BLOCK", 900, "00:25:00Z"),
    seat(2030010200002, "APPROVE", null, "00:35:00Z"),
    seat(2030010200003, null, null, "00:36:00Z"),
  ], joins, branchPr);
  const items = itemEvents([
    { repo: "s2w", id: 9000, number: 900, is_pr: false, created_at: `${day}00:00:00Z`, actor: "maintainer", body: null },
    { repo: "lifeos", id: 9002, number: 900, is_pr: false, created_at: `${day}00:05:00Z`, actor: "bot", body: null },
    {
      repo: "s2w", id: 9001, number: 901, is_pr: true, created_at: `${day}00:40:00Z`, actor: "maintainer",
      body: "Part of #900", head_sha: shas[1], head_ref: "feat/900-widget", base_ref: "main",
      merged_at: `${day}00:58:00Z`, merge_commit_sha: shas[2], closed_by: "maintainer",
    },
  ], joins);
  const timeline = timelineEvents([
    { repo: "s2w", number: 900, ordinal: 0, id: 77001, event: "labeled", created_at: `${day}00:00:01Z`, actor: "maintainer", label: "pts:2" },
    { repo: "s2w", number: 900, ordinal: 1, id: null, event: "cross-referenced", created_at: `${day}00:40:01Z`, actor: "maintainer", ref_number: 901 },
    { repo: "s2w", number: 900, ordinal: 2, id: 77003, event: "commented", created_at: `${day}00:45:00Z`, actor: "maintainer", comment_bytes: 312 },
    { repo: "s2w", number: 900, ordinal: 3, id: 77004, event: "subscribed", created_at: `${day}00:45:01Z`, actor: "maintainer" },
  ], joins);
  const commits = commitEvents([
    { repo: "s2w", sha: shas[0], parents: [], author: "maintainer", committed: `${day}00:10:00Z`, subject: "base", co_authored: false },
    { repo: "s2w", sha: shas[1], parents: [shas[0]], author: "maintainer", committed: `${day}00:19:00Z`, subject: "feat: widget (#900)", co_authored: true },
    { repo: "s2w", sha: shas[2], parents: [shas[0], shas[1]], author: "maintainer", committed: `${day}00:58:00Z`, subject: "merge (#901)", co_authored: false },
  ], joins);
  const sprints = sprintEvents([{ sprint: 1, slot: "2030-01-02-1a", ts: `${day}00:00:00Z`, file_id: "2030-01-02-1" }]);
  const events = window([...legs, ...seats, ...items, ...timeline, ...commits, ...sprints], `${day}00:00:00Z`, `${day}01:00:00Z`);
  const { sse } = render([
    `${MARK}synthetic generated by research/h-measure/private/fixture.ts; fake numbers and shas, not captured`,
    "node --experimental-strip-types research/h-measure/private/fixture.ts --write",
    `events=${events.length} dropped=timeline-other-kind:1,worker-other-repo:1`,
  ], events);
  assertClean(sse);
  return sse;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const sse = synthetic();
  if (process.argv.includes("--write")) writeFileSync(FIXTURE_PATH, sse);
  else process.stdout.write(sse);
}
