// Gate-3 summary (s2w#374 PR 3): reads the 30 score reports (`--json`) and the 20 committed
// mappings under research/h-measure/ and prints the results table, the five contract B4 items
// per stream, and the grading of the predictions comment (issuecomment-5938191252).
// No number is typed by hand. Run from the repo root:
//   node research/h-measure/gate3-summary.ts > research/h-measure/results/gate3/summary.md
import { readFileSync } from "node:fs";

const R = "research/h-measure";
const KS = [2, 3, 4, 5, 6];
const STREAMS = ["obf", "private"];
const ARMS = ["h", "h-s2", "b3"];
const rd = (p) => JSON.parse(readFileSync(p, "utf8"));
const f4 = (x) => (x === null || x === undefined ? "undefined" : x.toFixed(4));
const mean = (a) => a.reduce((s, x) => s + x, 0) / a.length;

const row = {}; // row[stream][arm][k]
for (const s of STREAMS) {
  row[s] = {};
  for (const a of ARMS) {
    row[s][a] = {};
    for (const k of KS) {
      const d = rd(`${R}/results/gate3/${a}.${s}.r${k}.json`);
      const g = d.keys[0].grade;
      const committed =
        a === "h"
          ? null
          : rd(`${R}/committed/${a}.${s === "obf" ? `obf-r${k}-dev` : "private-dev-2"}.r${k}.json`);
      row[s][a][k] = {
        p: g.mapping.micro.precision,
        r: g.mapping.micro.recall,
        f1: g.mapping.micro.f1,
        fm: g.mapping.false_merge,
        rec: g.mapping.recovery,
        ep: g.edges.micro.precision,
        er: g.edges.micro.recall,
        ef1: g.edges.micro.f1,
        usd: committed ? committed.spend.usd : 0,
        failure: committed ? committed.failure : null,
        nmFirst: committed ? committed.no_match.first : null,
        nmAfter: committed ? committed.no_match.after : null,
        probe: committed ? committed.probe.reply : null,
        attempts: committed ? committed.attempts : null,
        fits: committed && a === "b3" ? committed.budget.fits.length : null,
        key: d.keys[0].file,
      };
    }
  }
}
const col = (s, a, f) => KS.map((k) => row[s][a][k][f]);
const out = [];
const p = (x = "") => out.push(x);

p("# Gate 3 results (s2w#374 PR 3)");
p();
p("Generated by `research/h-measure/gate3-summary.ts` from the 30 `--json` reports in this directory and the 20 committed files. Test span: `obf-rK-reserved-6` under `dev-key-v3.obf-rK.json` (obfuscated), `private-test-2` under `private-key-v2.json` (private). Identity P / R / F1 are the mention-micro B-cubed values; false-merge is mention-weighted; recovery is entity recovery; edge columns are the relationship grade (`undefined` = no edge precision or F1 defined). `usd` is the arm's committed spend.");
for (const s of STREAMS) {
  p();
  p(`## ${s === "obf" ? "Obfuscated stream" : "Private stream"}`);
  p();
  p("| arm | K | P | R | F1 | false-merge | recovery | edge P | edge R | edge F1 | usd |");
  p("|---|---|---|---|---|---|---|---|---|---|---|");
  for (const a of ARMS)
    for (const k of KS) {
      const x = row[s][a][k];
      p(`| ${a} | r${k} | ${f4(x.p)} | ${f4(x.r)} | ${f4(x.f1)} | ${f4(x.fm)} | ${f4(x.rec)} | ${f4(x.ep)} | ${f4(x.er)} | ${f4(x.ef1)} | ${x.usd.toFixed(4)} |`);
    }
}

p();
p("## Means over r2 to r6");
p();
p("| stream | arm | F1 | P | false-merge | recovery | edge F1 (defined replicates) | usd total |");
p("|---|---|---|---|---|---|---|---|");
for (const s of STREAMS)
  for (const a of ARMS) {
    const ef = col(s, a, "ef1").filter((x) => x !== null);
    p(`| ${s} | ${a} | ${f4(mean(col(s, a, "f1")))} | ${f4(mean(col(s, a, "p")))} | ${f4(mean(col(s, a, "fm")))} | ${f4(mean(col(s, a, "rec")))} | ${ef.length ? f4(mean(ef)) : "undefined"} (${ef.length} of 5) | ${col(s, a, "usd").reduce((x, y) => x + y, 0).toFixed(4)} |`);
  }

// ---- Contract B4 items (plan §5) ----
const items = {};
p();
p("## Contract B4 items (per stream)");
p();
p("Item 2c uses relationship F1; an undefined mean fails the item (plan §5: undefined counts as a fail).");
p();
p("| item | obfuscated | private |");
p("|---|---|---|");
const detail = {};
for (const s of STREAMS) {
  const F = (a) => col(s, a, "f1");
  const gain1 = mean(F("h-s2").map((x, i) => x - F("h")[i]));
  const all1 = F("h-s2").every((x, i) => x > F("h")[i]);
  const fmH = mean(col(s, "h", "fm")), fmS = mean(col(s, "h-s2", "fm"));
  const efH = col(s, "h", "ef1"), efS = col(s, "h-s2", "ef1");
  const efDef = efH.every((x) => x !== null) && efS.every((x) => x !== null);
  const efGap = efDef ? mean(efH) - mean(efS) : null;
  const i2a = col(s, "h-s2", "fm").every((x) => x <= 0.05);
  const i2b = fmS - fmH <= 0.02;
  const i2c = efGap !== null && efGap <= 0.05;
  const rec = mean(col(s, "h-s2", "rec"));
  const gain4 = mean(F("h-s2").map((x, i) => x - F("b3")[i]));
  const n4 = F("h-s2").filter((x, i) => x > F("b3")[i]).length;
  const hmean = mean(F("h"));
  // contract: "$5 of API spend per stream per replicate" = both arms of one replicate together
  const maxUsd = Math.max(...KS.map((k) => row[s]["h-s2"][k].usd + row[s].b3[k].usd));
  const failures = ["h-s2", "b3"].flatMap((a) => col(s, a, "failure")).filter((x) => x);
  const i1 = hmean <= 0.9 && gain1 >= 0.1 && all1;
  const i3 = rec >= 0.6;
  const i4 = gain4 >= 0.05 && n4 >= 4;
  const i5 = maxUsd <= 5 && failures.length === 0;
  detail[s] = { gain1, all1, hmean, fmH, fmS, i2a, i2b, efGap, i2c, rec, gain4, n4, maxUsd, failures, i1, i3, i4, i5 };
  items[s] = [i1, i2a && i2b && i2c, i3, i4, i5];
}
const d = detail;
const pf = (b) => (b ? "pass" : "fail");
p(`| 1 primary: mean F1 gain over H >= 0.10 and higher in all 5 | ${pf(d.obf.i1)} (H mean ${f4(d.obf.hmean)}, gain ${f4(d.obf.gain1)}, higher in all 5: ${d.obf.all1}) | ${pf(d.private.i1)} (H mean ${f4(d.private.hmean)}, gain ${f4(d.private.gain1)}, higher in all 5: ${d.private.all1}) |`);
p(`| 2a false-merge <= 0.05 every replicate | ${pf(d.obf.i2a)} | ${pf(d.private.i2a)} |`);
p(`| 2b mean false-merge no more than 0.02 above H (H ${f4(d.obf.fmH)} / ${f4(d.private.fmH)}, H+S2 ${f4(d.obf.fmS)} / ${f4(d.private.fmS)}) | ${pf(d.obf.i2b)} | ${pf(d.private.i2b)} |`);
p(`| 2c mean relationship F1 no more than 0.05 below H (gap ${f4(d.obf.efGap)} / ${f4(d.private.efGap)}) | ${pf(d.obf.i2c)} | ${pf(d.private.i2c)} |`);
p(`| 3 mean entity recovery >= 0.60 (${f4(d.obf.rec)} / ${f4(d.private.rec)}) | ${pf(d.obf.i3)} | ${pf(d.private.i3)} |`);
p(`| 4 mean F1 gain over B3 >= 0.05 and higher in >= 4 of 5 (gain ${f4(d.obf.gain4)}, ${d.obf.n4} of 5 / gain ${f4(d.private.gain4)}, ${d.private.n4} of 5) | ${pf(d.obf.i4)} | ${pf(d.private.i4)} |`);
p(`| 5 budget: h-s2 + B3 spend per replicate <= $5, no failure (max ${d.obf.maxUsd.toFixed(4)} / ${d.private.maxUsd.toFixed(4)}) | ${pf(d.obf.i5)} | ${pf(d.private.i5)} |`);
const verdict = (s) => {
  const it = items[s];
  const first = it.findIndex((x) => !x);
  if (detail[s].hmean > 0.9) return "insufficient headroom to show added value (not a pass)";
  return first < 0 ? "pass" : `fail (first failing item: ${first + 1})`;
};
p();
p(`**Obfuscated stream: ${verdict("obf")}. Private stream: ${verdict("private")}. Gate 3: ${items.obf.every(Boolean) && items.private.every(Boolean) ? "pass" : "fail"} (each stream must pass on its own).**`);

// ---- Predictions ----
const cl = []; // [group, clause, measured, hit]
const inr = (x, lo, hi) => x >= lo && x <= hi;
const rg = (a) => `${f4(Math.min(...a))} to ${f4(Math.max(...a))}`;
{
  const g = "H obf";
  const F = col("obf", "h", "f1");
  cl.push([g, "F1 in [0.78, 0.84] every replicate", rg(F), F.every((x) => inr(x, 0.78, 0.84))]);
  const P = col("obf", "h", "p");
  cl.push([g, "P >= 0.98 every replicate", rg(P), P.every((x) => x >= 0.98)]);
  const Rc = col("obf", "h", "rec");
  cl.push([g, "recovery >= 0.95 every replicate", rg(Rc), Rc.every((x) => x >= 0.95)]);
  const EP = col("obf", "h", "ep");
  cl.push([g, "edge P in [0.35, 0.55] every replicate", rg(EP), EP.every((x) => inr(x, 0.35, 0.55))]);
  const ER = col("obf", "h", "er");
  cl.push([g, "edge R in [0.15, 0.30] every replicate", rg(ER), ER.every((x) => inr(x, 0.15, 0.3))]);
  cl.push([g, "F1 below 0.90 every replicate (margin exists)", rg(F), F.every((x) => x < 0.9)]);
}
{
  const g = "H+S2 obf";
  const F = col("obf", "h-s2", "f1");
  cl.push([g, "mean F1 in [0.55, 0.85]", f4(mean(F)), inr(mean(F), 0.55, 0.85)]);
  cl.push([g, "spread (max - min) >= 0.10", f4(Math.max(...F) - Math.min(...F)), Math.max(...F) - Math.min(...F) >= 0.1]);
  const P = col("obf", "h-s2", "p");
  cl.push([g, "P >= 0.95 every replicate", rg(P), P.every((x) => x >= 0.95)]);
  const Rc = col("obf", "h-s2", "rec");
  cl.push([g, "mean recovery in [0.60, 0.95]", f4(mean(Rc)), inr(mean(Rc), 0.6, 0.95)]);
  const n = KS.filter((k) => row.obf["h-s2"][k].ef1 !== null && row.obf.h[k].ef1 !== null && Math.abs(row.obf["h-s2"][k].ef1 - row.obf.h[k].ef1) <= 0.1).length;
  cl.push([g, "edge F1 within 0.10 of H's in >= 3 of 5 (undefined never within)", `${n} of 5`, n >= 3]);
}
{
  const g = "B3 obf";
  const F = col("obf", "b3", "f1");
  cl.push([g, "mean F1 in [0.35, 0.75]", f4(mean(F)), inr(mean(F), 0.35, 0.75)]);
  const P = col("obf", "b3", "p");
  cl.push([g, "P >= 0.95 every replicate", rg(P), P.every((x) => x >= 0.95)]);
  const n = KS.filter((k) => row.obf.b3[k].f1 < row.obf["h-s2"][k].f1).length;
  cl.push([g, "below H+S2 in >= 3 of 5", `${n} of 5`, n >= 3]);
  const fits = col("obf", "b3", "fits");
  cl.push([g, "<= 2 fits per replicate", `${Math.min(...fits)} to ${Math.max(...fits)}`, fits.every((x) => x <= 2)]);
  const bf = col("obf", "b3", "failure").filter((x) => x);
  cl.push([g, "no budget-fit failure", `${bf.length} failures`, bf.length === 0]);
}
{
  const g = "H private";
  const F = col("private", "h", "f1");
  cl.push([g, "F1 < 0.20", rg(F), F.every((x) => x < 0.2)]);
  const P = col("private", "h", "p");
  cl.push([g, "P >= 0.90", rg(P), P.every((x) => x >= 0.9)]);
  const Rc = col("private", "h", "rec");
  cl.push([g, "recovery < 0.10", rg(Rc), Rc.every((x) => x < 0.1)]);
  const ER = col("private", "h", "er");
  cl.push([g, "edge R <= 0.01", rg(ER), ER.every((x) => x <= 0.01)]);
  const noKey = (x) => JSON.stringify({ ...x, key: 0 });
  const same = KS.every((k) => noKey(row.private.h[k]) === noKey(row.private.h[2]));
  cl.push([g, "identical in all 5 replicates", same ? "identical" : "differs", same]);
}
{
  const g = "H+S2 private";
  const F = col("private", "h-s2", "f1");
  cl.push([g, "mean F1 in [0.30, 0.70]", f4(mean(F)), inr(mean(F), 0.3, 0.7)]);
  const Rc = col("private", "h-s2", "rec");
  cl.push([g, "mean recovery in [0.30, 0.70]", f4(mean(Rc)), inr(mean(Rc), 0.3, 0.7)]);
  const FM = col("private", "h-s2", "fm");
  cl.push([g, "false-merge <= 0.05 every replicate", rg(FM), FM.every((x) => x <= 0.05)]);
}
{
  const g = "B3 private";
  const F = col("private", "b3", "f1");
  cl.push([g, "mean F1 in [0.20, 0.60]", f4(mean(F)), inr(mean(F), 0.2, 0.6)]);
  const n = KS.filter((k) => row.private.b3[k].f1 < row.private["h-s2"][k].f1).length;
  cl.push([g, "below H+S2 in >= 3 of 5", `${n} of 5`, n >= 3]);
}
{
  const g = "No-match";
  const cnt = (s, a, f) => col(s, a, f).filter((x) => x === true).length;
  for (const s of STREAMS) {
    const h = cnt(s, "h-s2", "nmFirst"), b = cnt(s, "b3", "nmFirst");
    cl.push([g, `${s}: h-s2 pre-repair no-match 1 to 2 of 5`, `${h} of 5`, h >= 1 && h <= 2]);
    cl.push([g, `${s}: B3 pre-repair no-match 0 to 1 of 5`, `${b} of 5`, b <= 1]);
    const ha = cnt(s, "h-s2", "nmAfter"), ba = cnt(s, "b3", "nmAfter");
    cl.push([g, `${s}: post-repair no-match 0 of 5 for h-s2 and B3`, `h-s2 ${ha}, B3 ${ba}`, ha === 0 && ba === 0]);
  }
}
{
  const g = "Spend";
  const hs = STREAMS.flatMap((s) => col(s, "h-s2", "usd")), bs = STREAMS.flatMap((s) => col(s, "b3", "usd"));
  const all = [...hs, ...bs];
  const tot = all.reduce((s, x) => s + x, 0);
  cl.push([g, "h-s2 $0.15 to $0.35 per replicate", `${Math.min(...hs).toFixed(4)} to ${Math.max(...hs).toFixed(4)}`, hs.every((x) => inr(x, 0.15, 0.35))]);
  cl.push([g, "B3 $0.40 to $1.50 per replicate", `${Math.min(...bs).toFixed(4)} to ${Math.max(...bs).toFixed(4)}`, bs.every((x) => inr(x, 0.4, 1.5))]);
  cl.push([g, "no replicate above $3.50", `max ${Math.max(...all).toFixed(4)}`, all.every((x) => x <= 3.5)]);
  const fl = STREAMS.flatMap((s) => ["h-s2", "b3"].flatMap((a) => col(s, a, "failure"))).filter((x) => x);
  cl.push([g, "no budget failure on any arm", `${fl.length} failures`, fl.length === 0]);
  // failed-probe spend ($0.0859, ledger.md) sits in no committed file; adding it still misses the band
  cl.push([g, "run total $6 to $20", `$${tot.toFixed(4)} committed (+$0.0859 failed probes, ledger.md)`, inr(tot + 0.0859, 6, 20)]);
}
{
  const g = "Probe";
  const rep = STREAMS.flatMap((s) => ["h-s2", "b3"].flatMap((a) => col(s, a, "probe")));
  cl.push([g, "every probe answers none", `${rep.filter((x) => x === "none").length} of ${rep.length}`, rep.every((x) => x === "none")]);
  const att = STREAMS.flatMap((s) => ["h-s2", "b3"].flatMap((a) => col(s, a, "attempts")));
  const reruns = att.filter((x) => x > 1).length;
  cl.push([g, "at most one probe re-run in all 20", `${reruns} (files with attempts > 1)`, reruns <= 1]);
}
{
  const g = "Gate";
  cl.push([g, "obfuscated item 1 fails", pf(d.obf.i1), !d.obf.i1]);
  cl.push([g, "obfuscated items 2 and 5 pass", `2: ${pf(items.obf[1])}, 5: ${pf(items.obf[4])}`, items.obf[1] && items.obf[4]]);
  cl.push([g, "private item 1 passes", pf(d.private.i1), d.private.i1]);
  cl.push([g, "private item 3 fails (predicted to decide)", `item 3: ${pf(d.private.i3)}`, !d.private.i3]);
  const gate = items.obf.every(Boolean) && items.private.every(Boolean);
  cl.push([g, "point estimate for the gate: fail", gate ? "pass" : "fail", !gate]);
}
p();
p("## Predictions (issuecomment-5938191252), clause by clause");
p();
p("A clause is a hit when its measured value satisfies it. A prediction row is a hit only when every clause in its group is a hit.");
p();
p("| # | prediction row | clause | measured | hit |");
p("|---|---|---|---|---|");
cl.forEach((c, i) => p(`| ${i + 1} | ${c[0]} | ${c[1]} | ${c[2]} | ${c[3] ? "hit" : "miss"} |`));
const hits = cl.filter((c) => c[3]).length;
const groups = [...new Set(cl.map((c) => c[0]))];
const gh = groups.filter((g) => cl.filter((c) => c[0] === g).every((c) => c[3])).length;
p();
p(`**Clauses: ${hits} of ${cl.length} hit. Prediction rows: ${gh} of ${groups.length} hit** (${groups.map((g) => `${g}: ${cl.filter((c) => c[0] === g && c[3]).length} of ${cl.filter((c) => c[0] === g).length}`).join("; ")}).`);
process.stdout.write(out.join("\n") + "\n");
