//! Check 19, public API snapshots (s2w#68, plan #44 PR-6): every workspace crate with a lib
//! target has its public API committed as `xtask/public-api/<crate>.txt`, and a PR whose code
//! no longer matches the snapshot fails. `cargo xtask api` runs the comparison alone;
//! `cargo xtask api --update` rewrites the snapshots, and the resulting diff is what review reads.
//!
//! Source is read as `syn` ASTs on stable Rust, not rustdoc JSON (nightly). The workspace
//! forbids `unreachable_pub`, so every item spelled `pub` is reachable from its crate root and
//! is public API; collecting the `pub` items of the non-test module tree is therefore sound for
//! what is exported. One line per item, `<module>: <tokens>`, bodies and docs stripped, sorted,
//! so a body, doc or item-order change never churns a snapshot. Trait impls are recorded by
//! header (plus associated types and consts) unless the self type is a private local type.
//!
//! Blind spots, accepted (karpathy ruling on s2w#68; a nightly `cargo public-api` cross-check
//! is the follow-up): types are recorded as spelled, so a change to a `use` or re-export path
//! that re-points a name (`use a::Foo` → `use b::Foo`) changes the real API without changing
//! the snapshot, and a re-export is recorded as its `pub use` line, not expanded; auto traits
//! (`Send`, `Sync`, ...) and blanket impls are not recorded; items produced by macros other
//! than `#[derive]` (item-level `macro_rules!` calls, attribute macros) and `include!`d code
//! are invisible; `#[macro_export]` macros are recorded by name only; `const`/`static` values
//! are not recorded. Every `cfg` arm is read and its attribute kept on the line, so a snapshot
//! is the same on every host.
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;
use std::process::ExitCode;

use crate::module_size::walk::Scan;

mod render;
#[cfg(test)]
mod tests;

const DIR: &str = "xtask/public-api";
const UPDATE: &str = "cargo xtask api --update";

/// Runs check 19 against the committed snapshots.
pub(super) fn check(root: &Path, meta: &super::Metadata) -> Vec<String> {
    match snapshots(meta) {
        Ok(actual) => compare(&committed(root), &actual),
        Err(problems) => problems,
    }
}

/// `cargo xtask api [--update]`.
pub(super) fn run(root: &Path, args: &[String]) -> ExitCode {
    let update = args == ["--update"];
    if !args.is_empty() && !update {
        eprintln!("usage: cargo xtask api [--update]");
        return ExitCode::from(2);
    }
    let problems = match super::metadata(root).and_then(|meta| snapshots(&meta)) {
        Ok(actual) if update => write(root, &actual),
        Ok(actual) => compare(&committed(root), &actual),
        Err(problems) => problems,
    };
    if problems.is_empty() {
        println!("✓ public API matches {DIR}/");
        return ExitCode::SUCCESS;
    }
    for p in &problems {
        eprintln!("✗ {p}");
    }
    ExitCode::FAILURE
}

/// The snapshot text of every lib crate, by package name.
fn snapshots(meta: &super::Metadata) -> Result<BTreeMap<String, String>, Vec<String>> {
    let mut out = BTreeMap::new();
    let mut problems = Vec::new();
    for pkg in &meta.packages {
        for target in pkg.targets.iter().filter(|t| t.is_lib()) {
            let mut scan = Scan::default();
            if let Err(e) = scan.file(&target.src_path, target.name.replace('-', "_"), true) {
                problems.push(e);
            }
            // A module the walker could not open hides its items; `include!`-family findings
            // are the size check's concern (data, or the documented `include!` blind spot).
            let unseen: Vec<&str> = scan
                .findings
                .iter()
                .map(String::as_str)
                .filter(|f| !f.contains("include! macros"))
                .collect();
            if !unseen.is_empty() {
                problems.push(format!(
                    "{}: public API not read ({}); fix the module layout first",
                    pkg.name,
                    unseen.join("; ")
                ));
            }
            out.insert(
                pkg.name.clone(),
                text(&pkg.name, &render::crate_lines(&scan.asts)),
            );
        }
    }
    if out.is_empty() {
        problems.push(
            "no workspace crate has a lib target; cargo metadata or the walker is broken"
                .to_owned(),
        );
    }
    if problems.is_empty() {
        Ok(out)
    } else {
        Err(problems)
    }
}

fn text(krate: &str, lines: &BTreeSet<String>) -> String {
    let mut s = format!(
        "# Public API of {krate}. Generated by `{UPDATE}`; review the diff, do not hand-edit.\n"
    );
    for line in lines {
        s.push_str(line);
        s.push('\n');
    }
    s
}

/// The committed snapshots, by file stem; an unreadable directory reads as empty.
fn committed(root: &Path) -> BTreeMap<String, String> {
    let Ok(entries) = fs::read_dir(root.join(DIR)) else {
        return BTreeMap::new();
    };
    entries
        .flatten()
        .filter_map(|e| {
            let path = e.path();
            let stem = path.file_stem()?.to_str()?.to_owned();
            (path.extension()? == "txt").then_some(())?;
            Some((stem, fs::read_to_string(&path).unwrap_or_default()))
        })
        .collect()
}

/// Findings comparing committed snapshots with the code; each names the next action.
fn compare(committed: &BTreeMap<String, String>, actual: &BTreeMap<String, String>) -> Vec<String> {
    let mut problems = Vec::new();
    for (krate, now) in actual {
        let Some(was) = committed.get(krate) else {
            problems.push(format!(
                "{krate} has no public API snapshot; run `{UPDATE}` and commit {DIR}/{krate}.txt in this PR"
            ));
            continue;
        };
        if was == now {
            continue;
        }
        let was: BTreeSet<&str> = was.lines().collect();
        let now: BTreeSet<&str> = now.lines().collect();
        let mut diff: Vec<String> = now.difference(&was).map(|l| format!("  + {l}")).collect();
        diff.extend(was.difference(&now).map(|l| format!("  - {l}")));
        let more = diff.len().saturating_sub(20);
        diff.truncate(20);
        if more > 0 {
            diff.push(format!("  …and {more} more"));
        }
        problems.push(format!(
            "{krate}'s public API differs from {DIR}/{krate}.txt (+ in code, - in snapshot):\n{}\n  if intended, run `{UPDATE}` and commit the snapshot",
            diff.join("\n")
        ));
    }
    for stale in committed.keys().filter(|k| !actual.contains_key(*k)) {
        problems.push(format!(
            "{DIR}/{stale}.txt names no lib crate in the workspace; delete it (or run `{UPDATE}`)"
        ));
    }
    problems
}

/// Rewrites every snapshot and deletes stale ones, printing what changed.
fn write(root: &Path, actual: &BTreeMap<String, String>) -> Vec<String> {
    let dir = root.join(DIR);
    let old = committed(root);
    let mut problems = Vec::new();
    if let Err(e) = fs::create_dir_all(&dir) {
        return vec![format!("{}: {e}", dir.display())];
    }
    for (krate, now) in actual {
        if old.get(krate) != Some(now) {
            match fs::write(dir.join(format!("{krate}.txt")), now) {
                Ok(()) => println!("updated {DIR}/{krate}.txt"),
                Err(e) => problems.push(format!("{DIR}/{krate}.txt: {e}")),
            }
        }
    }
    for stale in old.keys().filter(|k| !actual.contains_key(*k)) {
        match fs::remove_file(dir.join(format!("{stale}.txt"))) {
            Ok(()) => println!("removed {DIR}/{stale}.txt"),
            Err(e) => problems.push(format!("{DIR}/{stale}.txt: {e}")),
        }
    }
    problems
}
